export const INITIALIZE_APPLICATION                     = 'INITIALIZE_APPLICATION';
export const HANDLE_APPLICATION_INITIALIZATION_SUCCESS  = 'HANDLE_APPLICATION_INITIALIZATION_SUCCESS';
export const HANDLE_APPLICATION_INITIALIZATION_FAILURE  = 'HANDLE_APPLICATION_INITIALIZATION_FAILURE';
